### ISSUE TITLE
Error when hitting play

### ISSUE THREAD

**Issue by zellgoma** [AIDungeon/AIDungeon#180] opened 2019-12-16 21:20 UTC
I get an error when I hit play, specifically "ModuleNotFoundError: No module named 'regex._regex'; 'regex' is not a package"

I'm probably just doing something stupid, but I can't figure out what to do. 

Full log from hitting play:
Traceback (most recent call last):
  File "play.py", line 6, in <module>
    from generator.gpt2.gpt2_generator import *
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 7, in <module>
    from generator.gpt2.src import encoder, model, sample
  File "/content/AIDungeon/generator/gpt2/src/encoder.py", line 7, in <module>
    import regex as re
  File "/content/AIDungeon/venv/lib/python3.6/site-packages/regex.py", line 402, in <module>
    import _regex_core
  File "/content/AIDungeon/venv/lib/python3.6/site-packages/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'; 'regex' is not a package

**Comment by SoptikHa2** [comment] 2019-12-16 21:28
Duplicate of #179

**Closed** 2019-12-16 21:34 UTC
